Notebook pro experimenty s linearni regresi ve snaze ji dobre porozumet

In [1]:
import numpy as np

In [8]:
# nasimulujeme si nejaka data
X0 = np.ones([5,])
print(X0)

[1. 1. 1. 1. 1.]


In [15]:
X1 = np.array([2,5,1,6,7])
print(X1)

[2 5 1 6 7]


In [16]:
X2 = np.array([-6,-3,-4,-7,0])
print(X2)

[-6 -3 -4 -7  0]


In [17]:
Y = np. array([23, 45, 34, 32, 1])
print(Y)

[23 45 34 32  1]


In [18]:
np.linalg.matrix_rank(np.array([X1, X2]))

2

(X1, X2) je LN soubor vektoru, protoze hodnost je 2 a je rovna poctu vektoru v souboru

In [20]:
X3 = 2 * X1

In [21]:
np.linalg.matrix_rank(np.array([X1, X3]))

1

X1 a X3 jsou pochpitelne LZ